SHELL := C:/PROGRA~1/Git/bin/bash.exe

TOPLEVEL_LANG   = verilog
SIM             = xsim

TOPLEVEL        = axis_loopback
VERILOG_SOURCES = ../rtl/axis_loopback.sv
MODULE          = test_linkup


PYTHON := C:/Users/saaed/anaconda3/envs/capstone-scapy/python.exe

# <-- hard force these so Makefile.inc cannot overwrite them
override PYTHON_ARCH := 64bit
override LIBPYTHON_LOC = C:/Users/saaed/anaconda3/envs/capstone-scapy/python311.dll

include C:/Users/saaed/anaconda3/envs/capstone-scapy/Lib/site-packages/cocotb_tools/makefiles/Makefile.sim